import type { Metadata } from "next";
import 'bootstrap/dist/css/bootstrap.min.css'
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import BootstrapProvider from "@/components/BootstrapProvider";
 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <head>
        {/* Google Fonts */}
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto+Condensed:wght@400;700&family=Roboto:wght@400;700&display=swap"
          rel="stylesheet"
        />

        {/* Font Awesome 5.15.0 */}
        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.0/css/all.min.css"
          rel="stylesheet"
        />

        {/* Bootstrap Icons */}
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css"
          rel="stylesheet"
        />
      </head>

      <body>
        <BootstrapProvider>
          <Header />
          {children}
          <Footer />
        </BootstrapProvider>
      </body>
    </html>
  );
}
